--todo, make this automatic
resource.AddFile( "materials/autobox/scoreboard/badges/chumtoad.png" )
resource.AddFile( "materials/autobox/scoreboard/badges/win98.png" )
resource.AddFile( "materials/autobox/scoreboard/badges/menacing.png" )
autobox.badge:RegisterBadge("u_virus","Supreme Autist","This person is extremely autistic!",1,"materials/icon16/accept.png")
autobox.badge:RegisterBadge("u_nachovy","Æ","haha furryman purple guy.",1,"materials/icon16/flag_purple.png")
autobox.badge:RegisterBadge("u_moomoobeef","Win98 User","This person is running Windows 98.",1,"materials/autobox/scoreboard/badges/win98.png")
autobox.badge:RegisterBadge("u_boggle","Bought Admin","Bought admin for $12.50",1,"materials/icon16/money_add.png")
autobox.badge:RegisterBadge("u_treemonkey","(Bob the Builder)","W R E N C H",1,"materials/icon16/wrench_orange.png")
autobox.badge:RegisterBadge("u_luigi","The Sportster","Loyal servant of the sports god.",1,"materials/icon16/sport_soccer.png")
autobox.badge:RegisterBadge("u_skatingskelly","Certified Retard","This person is retarded.",1,"materials/icon16/disconnect.png")
autobox.badge:RegisterBadge("u_senk","Dysfunctional TV","[No Description]",1,"materials/icon16/monitor_error.png")
autobox.badge:RegisterBadge("u_closedcaptions", "Chumtoad","bitches badge",1,"materials/autobox/scoreboard/badges/chumtoad.png")
autobox.badge:RegisterBadge("u_astro", "Master of the Bodge ","Trust me, I'm an engineer!",1,"materials/icon16/tux.png")
autobox.badge:RegisterBadge("u_tempest", "Bot","Made of metal.",1,"materials/icon16/cog.png")
autobox.badge:RegisterBadge("u_mane","Menacing","This person is very menacing.",1,"materials/autobox/scoreboard/badges/menacing.png")
//autobox.badge:RegisterBadge("arbitrary","Arbitrarily Special","This person is arbitrarily special!",1,"materials/icon16/medal_bronze_1.png")